application: takanashi-demo
version: 1
runtime: python27
api_version: 1
threadsafe: yes

inbound_services:
- warmup

skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?tests$
- ^(.*/)?test$
- ^Makefile
- ^COPYING.LESSER
- ^README.md
- \.gitignore
- ^\.git/.*
- \.*\.lint$
- ^_images/.*

handlers:
- url: /favicon\.ico
  mime_type: image/vnd.microsoft.icon
  static_files: static/icon/favicon.ico
  upload: static/icon/favicon.ico
- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt

- url: /javascripts/
  static_dir: javascripts
- url: /css/
  static_dir: css
- url: /imgs/
  static_dir: static/imgs

- url: /cron_jobs/.*
  script: cron_jobs.app
  login: admin

- url: .*
  script: main.app


libraries:
- name: jinja2
  version: "2.6"
- name: webapp2
  version: "2.5.1"
